# Generated by Django 5.1 on 2024-08-31 05:52

import builtins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=builtins.any)),
                ('date_of_birth', models.DateField(blank=True, null=builtins.any)),
                ('location', models.CharField(blank=True, max_length=100, null=builtins.any)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=builtins.any)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.jpg', null=builtins.any, upload_to='profile_images/')),
                ('cover_photo', models.ImageField(blank=True, null=builtins.any, upload_to='cover_photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
