# Generated by Django 5.1 on 2024-09-03 08:55

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_customuser_phone_no_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=builtins.any, upload_to='profile_images/'),
        ),
    ]
