# Generated by Django 5.1 on 2024-09-07 14:31

import builtins
import user_auth.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=builtins.any, storage=user_auth.storage.S3ImageStorage(), upload_to='cover_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=builtins.any, storage=user_auth.storage.S3ImageStorage(), upload_to='profile_images/'),
        ),
    ]
